caddyserver/xcaddy

README.md

I know we can omit the `builder.CaddyPlugin` but I added it for readability

readme: ensure the example is valid Go

---

README.md

The pull request adds go-gettable instructions for `xcaddy`.
@Mohammed90 
Signed-off-by: Ankur Srivastava <ankur.srivastava@email.de>

added go-get instructions for xcaddy in the README.md

---

builder.go

I find that customized platform is not work,  like this:
```go
builder := xcaddy.Builder{
Compile: xcaddy.Compile{
Platform: xcaddy.Platform{
OS:   "linux",
Arch: "amd64",
},
},
CaddyVersion: CaddyVersion,
Plugins:      []xcaddy.Dependency{},
}
```

make customized env effective

---

README.md

The func `Build` has two parameters:
```
func (b Builder) Build(ctx context.Context, outputFile string) error
```

update library usage in README.md

---

.goreleaser.yml

The releases of xcaddy don't need handcrafted release notes, so immediate publishing is fine.

ci: immediately publish releases on tags

---

builder.go
builder_test.go
cmd/xcaddy/main.go
environment.go

Fix for error caused by replace directives with version pinning:
```
2020/08/06 10:53:59 [INFO] Temporary folder: /go/src/x/y/service/cta-proxy/buildenv_2020-08-06-1053.131880924
2020/08/06 10:53:59 [INFO] Writing main module: /go/src/x/y/service/cta-proxy/buildenv_2020-08-06-1053.131880924/main.go
2020/08/06 10:53:59 [INFO] Initializing Go module
2020/08/06 10:53:59 [INFO] exec (timeout=10s): /usr/local/bin/go mod init caddy 
go: creating new go.mod: module caddy
2020/08/06 10:53:59 [INFO] Replace x/y => /go/src/x/y
2020/08/06 10:53:59 [INFO] exec (timeout=10s): /usr/local/bin/go mod edit -replace x/y=/go/src/x/y 
2020/08/06 10:53:59 [INFO] Replace github.com/apache/thrift => github.com/apache/thrift v0.0.0-20190309152529-a9b748bb0e02
2020/08/06 10:53:59 [INFO] exec (timeout=10s): …
```

support go.mod replace version pinning

---

cmd/xcaddy/main.go

Extract default output file to a function and reuse it in both runBuild and runDev

Fix runDev when running on windows

---

cmd/xcaddy/main.go
cmd/xcaddy/main_test.go

When normalizing the `importPath` it will try to write on `main.go` files with imports
like `github.com/caddyserver/xcaddy/c:\xcaddy`
The fix is basically changing from `path.Join(currentModule, strings.TrimPrefix(cwd, filepath.ToSlash(moduleDir)))` to `path.Join(currentModule, filepath.ToSlash(strings.TrimPrefix(cwd, moduleDir)))`

Fix main.go generation when executing on a windows machine

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml

FYI @Mohammed90 @mholt 
Three commits:
1. brings the `release.yml` in line with the `caddy` repo's, and adds simple `.deb` packaging (no extra files or scripting, just the `/usr/bin/xcaddy`)
2. brings the `ci.yml` in line with the `caddy` repo's, including testing on Go 1.15
3. adds Cloudsmith .deb publishing (which is why I'm marking this as draft, until https://github.com/caddyserver/caddy/pull/3941 is complete and tested)

ci: Pull updates from Caddy, build .deb as well

---

.github/workflows/release.yml

We're actually pushing to the `xcaddy` cloudsmith repo, not `testing` (copy-pasted from `caddy` repo, so it had the wrong string). Purely a visual bug.

ci: Fix echo message on Cloudsmith push

---

builder.go

As of go 1.16, the `go {build,test}` commands don't modify the go.mod and go.sum files (see: https://golang.org/issue/40728). We, therefore, have to run `go mod tidy` to ensure the go.mod and go.sum files are consistent with the module requirements.
Closes #46

Run `go mod tidy` in the build environment

---

README.md
builder.go
cmd/xcaddy/main.go

[Mercure](https://mercure.rocks) and [Vulcain](https://vulcain.rocks) now use Caddy. They are available as Caddy modules but also as standalone binaries build with [GoReleaser](https://goreleaser.com/).
I managed to use `xcaddy` to prepare the source code and `goreleaser` to cross-compile and package the binary: dunglas/mercure#398.
Currently, `xcaddy` always compiles the project. This proposed `XCADDY_NO_BUILD` environment variable allows to prepare the source code but not run `go build` to save some CI time (`go build` is run by GoReleaser).

feat: add XCADDY_NO_BUILD to not run go build

---

cmd/xcaddy/main.go

To match the change in 623c3617263ddcceea808ea4e7edcc6ebe43a837, this resolves the replacement path ahead of time for `xcaddy build`.
My usecase is to make this command work:
```
$ xcaddy build --with github.com/caddyserver/caddy/v2=../../../caddy
```
Before this change, the output would read:
```
$ .\xcaddy.exe build --with github.com/caddyserver/caddy/v2=..\..\..\caddy                             2021/02/13 19:53:13 [INFO] Temporary folder: C:\Users\lavof\AppData\Local\Temp\buildenv_2021-02-13-1953.141206587
2021/02/13 19:53:13 [INFO] Writing main module: C:\Users\lavof\AppData\Local\Temp\buildenv_2021-02-13-1953.141206587\main.go
2021/02/13 19:53:13 [INFO] Initializing Go module
2021/02/13 19:53:13 [INFO] exec (timeout=10s): C:\Users\lavof\scoop\shims\go.exe mod init caddy
go: creating …
```

Resolve relative replacements for `xcaddy build` as well

---

cmd/xcaddy/main.go
cmd/xcaddy/main_test.go

accept replacements with branches of github forks

---

README.md
builder.go
cmd/xcaddy/main.go

**Fixes**: #61 
Allow building a debug output by setting `XCADDY_DEBUG=1` for `xcaddy` command.
**Examples**:
```bash
XCADDY_DEBUG=1 xcaddy build --with github.com/xxx/xxx=$(pwd)
XCADDY_DEBUG=1 xcaddy run
```

feat: enable DWARF debug info in the build by setting XCADDY_DEBUG=1

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml
cmd/main.go
cmd/main_test.go
cmd/xcaddy/main.go

Fix #22
It's not really useful to get Caddy's version when in dev mode anyways, and you can get full version information with `xcaddy list-modules --versions` if you _really_ need to... so "hiding" `caddy version` in dev mode to show `xcaddy`'s version instead seems totally fine.
I moved the `main.go` up a dir to match how Caddy does it for grabbing version information via having a level of indirection.
Sorry about the diff, `git` hates moving files when they have the same name. Please look at the first commit [`e6f588a`](https://github.com/caddyserver/xcaddy/pull/67/commits/e6f588a04ea819b21fc4c97298531f2ec24a05bf) on its own to see the _actual_ new code for grabbing the version.

cmd: Add `xcaddy version` command

---

.github/workflows/ci.yml
.github/workflows/release.yml

GoReleaser v0.177.0 fixes the issue, so the workaround is no longer needed.

ci: revert goreleaser workaround precereating caddy-build

---

README.md

Also updates the apt commands according to https://github.com/caddyserver/website/pull/177
Removed the note about "still in development" and "v2 only" because at this point, I think `xcaddy` is pretty much stable, and v1 has been EOL for nearly a year.

docs: Update README to mention `xcaddy version`, cleanup

---

cmd/main.go

The env var `XCADDY_SKIP_BUILD` is supposed to imply `XCADDY_SKIP_CLEANUP`, but the implementation missed this detail. The `Builder#Build` method has `defer buildEnv.Close()`, which runs even on the early exit here:
https://github.com/caddyserver/xcaddy/blob/c7959560b56ec05306fd16f26d1b83e1f8272a40/builder.go#L80-L86
The `environment#Close` method does not know about `(Builder).SkipBuild`. We can overload the `skipCleanup` semantics because skipping build implies skipping cleanup.

fix: skip cleanup if build is skipped

---

environment.go

For some reason, downloading the dependencies resolves away the ambiguity. It is not clear why that is and is currently being researched.
Fixes caddyserver/caddy#4331

run `go get -d` at the end of prepping new env

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.gitignore
.golangci.yml
environment.go

I thought it would be helpful to log out the generated `main.go` in the logs, because sometimes it's nice to use the xcaddy logs as a report to Go upstream when we have some strange issues with building. Makes it easier to take the logs, tidy them up as reproduction steps, and post them somewhere.
Example:
```
$ xcaddy build --with github.com/caddy-dns/cloudflare
2022/04/06 16:38:10 [INFO] Temporary folder: /tmp/buildenv_2022-04-06-1638.383429390
2022/04/06 16:38:10 [INFO] Writing main module: /tmp/buildenv_2022-04-06-1638.383429390/main.go
package main
import (
caddycmd "github.com/caddyserver/caddy/v2/cmd"
// plug in Caddy modules here
_ "github.com/caddyserver/caddy/v2/modules/standard"
_ "github.com/caddy-dns/cloudflare"
)
func main() {
caddycmd.Main()
}
2022/04/06 16:38:10 [INFO] …
```

Log out main.go contents, update CI

---

environment.go

Fixes #54
For example:
```
$ xcaddy build v2.3.0 --with github.com/caddy-dns/cloudflare
...
2022/04/06 01:54:25 [INFO] Initializing Go module
2022/04/06 01:54:25 [INFO] exec (timeout=10s): go mod init caddy
2022/04/06 01:54:26 [INFO] Pinning versions
2022/04/06 01:54:26 [INFO] exec (timeout=0s): go get -d -v github.com/caddyserver/caddy/v2@v2.3.0
...
2022/04/06 01:54:27 [INFO] exec (timeout=0s): go get -d -v github.com/caddy-dns/cloudflare github.com/caddyserver/caddy/v2@v2.3.0
go: github.com/caddy-dns/cloudflare@upgrade (v0.0.0-20210607183747-91cf700356a1) requires github.com/caddyserver/caddy/v2@v2.4.0, not github.com/caddyserver/caddy/v2@v2.3.0
2022/04/06 01:54:28 [FATAL] exit status 1
```
The key being that the `go get` to add the `cloudflare` plugin _also_ specifies the Caddy module, …

Prevent main Caddy module from upgrading from adding a plugin

---

README.md
builder.go
cmd/main.go
environment.go
go.mod
go.sum

Add environment variable
XCADDY_GOBUILDFLAGS
to override default build arguments from environment (close #102).
To support flags with variable arguments Unix-style quoting is supported.

Enable overriding build flags from environment

---

builder.go
environment.go

Commit 47f9ded5d83ca8e701852ca7ad57cd3453e6f988 is not sufficient alone to
ensure that all go modules are installed with write bit set because 'go mod'
or 'go get' might install submodules of other modules as read-only.
If set, the environment variable appends '-modcacherw' to go mod and go get
to ensure that submodules of other modules have write access.

Inject `XCADDY_GO_BUILD_FLAGS` through `go` operations (#102)

---

README.md
builder.go
cmd/main.go
environment.go

This is a follow-up to #110, as mentioned in https://github.com/caddyserver/xcaddy/pull/110#pullrequestreview-1074662198.
CC/ @akeskimo

core: add `XCADDY_GO_MOD_FLAGS` env var to allow passing custom `go mod` flags

---

cmd/main.go

Hi @mholt,
you were right #116 is a windows specific problem. I found this more detailed issue https://github.com/golang/go/issues/43724 were the reasons for the change are described.
> To recap how we got here, the fundamental problem is that lots of Go programs do things like exec.Command("prog") and expect that prog will come from a system directory listed in the PATH. It is a surprise and in some cases a security problem that on Windows prog will be taken from dot instead when prog.exe (or prog.bat, prog.com, ...) exists.
Because there is a special case in [getCaddyOutputFile](https://github.com/caddyserver/xcaddy/blob/0bd3c1dfd5c43841f23a198695aa1dee6488eb7c/cmd/main.go#L166) for windows xcaddy does exactly that, but it really wants to use the binary from the current directory.
> …

fix: xcaddy run on windows with go 1.19

---

.goreleaser.yml
README.md
cmd/main.go

Fix #128 
Haven't tested this yet. But it should be straight-forwards.
One detail I'm not sure how to handle is `sudo`. The `runDev` version of the code uses `sudo` by default, and that seems reasonable since a dev account is _probably_ a regular user and not root. But this purpose of the `runBuild` version is to run in Docker, which will be running as root. So having `sudo` would fail. I just added another env var to cover that case.
Is there a better way to automatically detect whether `sudo` should be used? I'm not sure how that should be done from Go.

Add support for setcap from `build` command

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/release.yml

See https://github.com/caddyserver/xcaddy/pull/132#issuecomment-1422834486
Same config/schedule (monthly) as https://github.com/caddyserver/caddy/pull/5258
I also manually updated the Actions once, so we don't get a similarly annoying PR-train like we did after https://github.com/caddyserver/caddy/pull/5258 :^)
The necessary fix for goreleaser's `replacements:` deprecation we dealt with in https://github.com/caddyserver/caddy/pull/5270, already happened in https://github.com/caddyserver/xcaddy/pull/129, so we should be good to go :)
But I guess we will see O.o

ci: enable dependabot to keep Actions versions up-to-date

---

.github/workflows/ci.yml
.github/workflows/release.yml

Essentially the same as https://github.com/caddyserver/caddy/pull/5271 :eyes: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: fix `set-output` deprecation

---

builder.go
environment.go

The struct fields for timeouts have always been there, just not used. We also used to use `exec.Command`, which is probably to building this package before the existence of `exec.CommandContext`. This PR fixes both of those observations.

core: pass `context.Context` to the command runner to adhere to timeouts, if set

---

builder.go

See the conversation in the gophers slack: https://gophers.slack.com/archives/C9BMAAFFB/p1683645084906259?thread_ts=1683329744.706999&cid=C9BMAAFFB
Help doc for `-e`:
> The -e flag causes tidy to attempt to proceed despite errors encountered while loading packages.
The effect is that some errors might be reported in stderr, but if non-critical it should ideally be able to push forwards and still complete tidying. If there's any more serious errors, `go build` should error out.

builder: Ignore tidy errors

---

environment.go

When compiling with specifying a timeout, the displayed timeout is a very large negative duration. Fix the display by checking whether there is a deadline.

check if context has a deadline

---

README.md

Though that turned out to not make any difference in the size of the binary this go around...

doc: fix typo '-w s' => '-w -s'

---

environment.go

Its simplicity making me worried I missed something

core: always inject the `nobadger` build tag

---

environment.go

When testing http3 graceful shutdown, I found out I can't build caddy with local plugin by `xcaddy build http3-graceful --with github.com/quic-go/quic-go=github.com/WeidiDeng/quic-go@graceful-close --with plugin=path`, I have to manually switch `with` positions.
Turns out the multiple replaces can be executed at once, so the order no longer matters.

execute module replacement in a single command

---

builder.go
environment.go

Fixes #181 
I haven't validated it yet. I might need to split `-tags` from `nobadger`.

bug: fix regression preventing `-trimpath` and trim of debug symbols

---

cmd/main.go
go.mod

Previously ".exe" will be added automatically when on windows, but not when cross compiling.

add ".exe" when cross compiling for windows

---

builder.go
cmd/main.go
internal/utils/environment.go

As said on Slack, some of the environmental variables are missing when building but they won't impact the build result because golang automatically fallbacks to `go env`.
No further action when build is skipped.

fix variable environment extraction

---

README.md
builder.go
cmd/main.go

~~Officially `--with` is used to add caddy modules to a caddy build. It can be used to change dependencies for a caddy build, i.e. change caddy core to a fork, use quic-go fork.~~
~~However, some dependencies can't be replaced this way, for example `golang.org/x/net` can't be replaced this way.~~
~~For dependencies this introduces a new grammar that a `~` prefix to a with to mean it's a dependency instead of a module.~~
~~I can't think why someone would want to name their plugin with a `~`, is it even allowed by golang? It will break caddy builds for those unfortunate souls.~~
Add `--with` option to replace dependency.
Also fixed when replacing, module version is lost. According to go [documents](https://go.dev/ref/mod#go-mod-edit), `If the @v in old@v is omitted, a replacement without a …

Add `--replace` for dependency replacement

---

README.md

Line 79 had "developing" written down as "devloping"

fix spelling error in readme

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml

I ran `goreleaser check` and the version field is the only thing it complained about.

ci: upgrade to goreleaser v2

---

io.go

I'm not sure if it has always been this way, but apparently using `--embed` with relative path results in an error. I figure turning the path into its absolute form avoids any embedding issue or confusion in tooling.

embed: turn source path to absolute for error-less copy

---

README.md

Resolves https://github.com/caddyserver/xcaddy/issues/203. I also added a little flavor text to draw attention to the filesystem line in the example.
I verified with a manual test that instantiating the filesystem with the same name as the `caddy.fs` module works fine.

docs: Add `embedded` filesystem declaration to `--embed` example

---

README.md
cmd/commands.go

Another small docs PR for `--embed` flag usage 🎏 
My main goal here was to add documentation for the way `--embed` behaves _without_ an alias for the source directory, which writes the contents of the source directory into the root* of the embedded FS without any containing subdirectory. This behavior, while perfectly ergonomic for making a file server, had confused me briefly as a new user (see #202).
Since the `--embed` examples in the README have been expanded + annotated, I removed the inline example from the command usage text in the source code. I think using this space for text that documents the unaliased behavior is worth it, but I'm happy to re-add the inline example if preferred.
<sub>*_yes, technically into the `/files` intermediate dir, but this is the root from the user's …

docs: Expand + clarify `--embed` docs, esp. for usage without alias

---

README.md

Addressing https://github.com/caddyserver/xcaddy/pull/206#discussion_r1772249221
These sneaked in unintentionally, sorry! It doesn't make sense to type a mostly-Caddyfile block as `sh`.
Also fixed my usage of spaces for indentation in the Caddyfile blocks in favor of tabs.

docs: Remove `sh` language hint from Caddyfile examples

---

.golangci.yml
builder.go

See https://github.com/caddyserver/caddy/pull/6655

chore: compile without nosql's support for Postgres and MySQL

---

builder.go

fix default build tags inclusion

---

builder.go

The following build failed on Windows with `Invalid Semantic Version` error.
`xcaddy build v2.8.4 --with github.com/caddyserver/caddy/v2=c:\Users\test\caddy`
The bug is among lines 97 - 110 in the builder.go.
```
// generating windows resources for embedding
if b.OS == "windows" {
// get version string, we need to parse the output to get the exact version instead tag, branch or commit
cmd := buildEnv.newGoBuildCommand(ctx, "list", "-m", buildEnv.caddyModulePath)
var buffer bytes.Buffer
cmd.Stdout = &buffer
err = buildEnv.runCommand(ctx, cmd)
if err != nil {
return err
}
// output looks like: github.com/caddyserver/caddy/v2 v2.7.6
version := strings.TrimSpace(strings.TrimPrefix(buffer.String(), buildEnv.caddyModulePath))
err = utils.WindowsResource(version, outputFile, buildEnv.tempFolder) …
```

Extract correct version when using --with flag to replace Caddy core

---

builder.go
environment.go
environment_test.go

It is a janky quick fix for #222.
@mohammed90

Append command flags before arguments

---

.gitignore
environment.go

Resolves #221 
Current behavior:
- xcaddy skips minor updates of lexical submodules
Intended behavior:
- xcaddy will ingest logically tagged and / or latest modules when semantically updated or a new release is available to @latest.
```shell
git clone https://github.com/infogulch/xtemplate && cd xtemplate
xcaddy build --with github.com/infogulch/xtemplate-caddy@v0.2.2 --with github.com/infogulch/xtemplate=.
go get github.com/infogulch/xtemplate-caddy@v0.2.2
xcaddy build --with github.com/infogulch/xtemplate-caddy@v0.2.5 --with github.com/infogulch/xtemplate=.
```
```shell
git clone https://github.com/jesssullivan/xcaddy && cd xcaddy
git checkout 221-fetch-uncached-modules
cd 221-xtemplate-caddy 
go mod tidy && go build -o xcaddy ./cmd/xcaddy
cd ../xtemplate
./xcaddy/xcaddy build --with …
```

bugfix- #221, xcaddy skips minor updates of lexical submodules
